sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "0.10"
install:
  - npm install
script:
  - npm test
after_success:
  - npm run semantic-release
